from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from app.config import get_settings
from app.schemas import ClassificationItem, InferenceResponse, SourceFileMetadata
from app.services.model_runtime import ModelRuntime
from app.services.model_store import ModelStore
from app.services.nifti_visualization import build_nifti_visualization


@dataclass
class InferenceInput:
    analysis_id: str
    patient_id: str
    patient_name: str
    modality: str
    clinician_email: str
    file_name: str
    file_mime_type: str
    file_size_bytes: int
    file_bytes: bytes


class InferenceService:
    def __init__(self) -> None:
        self.settings = get_settings()
        self.model_store = ModelStore()

    def run(self, payload: InferenceInput) -> InferenceResponse:
        model_name = self.settings.default_model_name
        model_version = self.settings.default_model_version
        try:
            model_path = self.model_store.resolve_model_path(model_name=model_name, model_version=model_version)
            runtime = ModelRuntime(model_path=model_path)
            runtime_result = runtime.run(file_bytes=payload.file_bytes, modality=payload.modality)
        except Exception as error:
            raise InferenceServiceError(str(error)) from error

        predicted_type = str(runtime_result.get("predicted_type") or "Unknown")
        confidence = float(runtime_result.get("confidence") or 0.0)
        confidence = max(0.0, min(1.0, confidence))
        proposed_tnm = str(runtime_result.get("tnm") or self.settings.model_default_tnm_stage)
        visualization = build_nifti_visualization(
            file_name=payload.file_name,
            file_bytes=payload.file_bytes,
            runtime_result=runtime_result,
        )

        segmentation_data = runtime_result.get("segmentation_data")
        if not isinstance(segmentation_data, dict):
            segmentation_data = {}

        if visualization:
            segmentation_data["visualization"] = visualization

        if not segmentation_data:
            segmentation_data = None

        findings = (
            f"Model predicts {predicted_type} with {round(confidence * 100)}% confidence "
            "based on lesion morphology and density patterns in the uploaded study."
        )

        return InferenceResponse(
            analysisId=payload.analysis_id,
            patientId=payload.patient_id,
            patientName=payload.patient_name,
            modality=payload.modality,
            clinicianEmail=payload.clinician_email,
            receivedAt=datetime.now(timezone.utc).isoformat(),
            sourceFile=SourceFileMetadata(
                name=payload.file_name,
                mimeType=payload.file_mime_type,
                sizeBytes=payload.file_size_bytes,
            ),
            findings=findings,
            cancerType=predicted_type,
            classificationConfidence=confidence,
            reasoning=str(runtime_result.get("reasoning") or "Prediction generated by model runtime."),
            proposedTnmStage=proposed_tnm,
            classifications=[
                ClassificationItem(
                    side="Left",
                    prediction=predicted_type,
                    confidence=confidence,
                    explanation="Primary left-side lesion demonstrates dominant malignant signature.",
                ),
                ClassificationItem(
                    side="Right",
                    prediction=predicted_type,
                    confidence=max(0.0, min(1.0, confidence - 0.03)),
                    explanation="Secondary right-side suspicious region with supporting radiographic traits.",
                ),
            ],
            segmentationData=segmentation_data,
            modelInfo={
                "modelName": model_name,
                "modelVersion": model_version,
                "modelSource": self.settings.model_source,
                "modelPath": str(model_path),
            },
        )


class InferenceServiceError(RuntimeError):
    pass
