from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

import numpy as np

from app.config import get_settings
from app.schemas import ClassificationItem, InferenceResponse, SourceFileMetadata
from app.services.model_runtime import ModelRuntime
from app.services.model_store import ModelStore
from app.services.nifti_visualization import (
    build_gradcam_overlay_volume,
    build_nifti_file_payload,
    build_nifti_visualization,
    build_rgb_nifti_file_payload,
    build_segmentation_overlay_volume,
    build_three_visualizations,
)
from app.services.segmentation_runtime import SegmentationRuntime
from app.services.tnm_staging import derive_tnm


@dataclass
class InferenceInput:
    analysis_id: str
    patient_id: str
    patient_name: str
    modality: str
    clinician_email: str
    file_name: str
    file_mime_type: str
    file_size_bytes: int
    file_bytes: bytes


class InferenceService:
    def __init__(self) -> None:
        self.settings = get_settings()
        self.model_store = ModelStore()
        self.segmentation_runtime = SegmentationRuntime()

    def run(self, payload: InferenceInput) -> InferenceResponse:
        model_name = self.settings.default_model_name
        model_version = self.settings.default_model_version
        try:
            tumor_mask = self.segmentation_runtime.segment(payload.file_bytes)
            model_path = self.model_store.resolve_model_path(model_name=model_name, model_version=model_version)
            runtime = ModelRuntime(model_path=model_path)
            runtime_result = runtime.run(
                file_bytes=payload.file_bytes,
                modality=payload.modality,
                tumor_mask=tumor_mask,
            )
        except Exception as error:
            raise InferenceServiceError(str(error)) from error

        predicted_type = str(runtime_result.get("predicted_type") or "Unknown")
        predicted_index: int = int(runtime_result.get("predicted_index") or 0)
        confidence = float(runtime_result.get("confidence") or 0.0)
        confidence = max(0.0, min(1.0, confidence))
        reasoning = str(runtime_result.get("reasoning") or "Prediction generated by model runtime.")

        all_class_probs: dict[str, float] = runtime_result.get("all_class_probs") or {}
        seg_mask: np.ndarray | None = runtime_result.get("seg_mask")
        seg_per_instance: np.ndarray | None = runtime_result.get("seg_per_instance")
        bbox: np.ndarray | None = runtime_result.get("bbox")

        # TNM staging (IASLC 9th edition, 2025), sized off the real tumour segmentation mask.
        tnm = derive_tnm(
            predicted_type=predicted_type,
            confidence=confidence,
            tumor_mask_3d=tumor_mask,
        )
        proposed_tnm = tnm["tnm_string"]

        # GradCAM++ visualization data
        gradcam_data = runtime.compute_gradcam(class_idx=predicted_index)

        # Build segmentation data payload
        segmentation_data: dict[str, Any] = {
            "tnmDetail": {
                "t":                   tnm["t"],
                "n":                   tnm["n"],
                "m":                   tnm["m"],
                "tnmString":           tnm["tnm_string"],
                "bestCaseStage":       tnm["best_case_stage"],
                "estimatedDiameterMm": tnm["estimated_diameter_mm"],
                "sizeMethod":          tnm["size_method"],
                "caveats":             tnm["caveats"],
                "edition":             tnm["edition"],
            },
        }

        if seg_mask is not None:
            # Downsample to 64×64 to keep the JSON payload manageable
            mask_small = _resize_mask(seg_mask, target=64)
            segmentation_data["segMask"] = {
                "data": mask_small.tolist(),
                "shape": list(mask_small.shape),
                "description": "Averaged per-instance sigmoid segmentation probability map",
            }

        if bbox is not None and len(bbox) >= 4:
            segmentation_data["boundingBox"] = {
                "xMin": round(float(bbox[0]), 4),
                "yMin": round(float(bbox[1]), 4),
                "xMax": round(float(bbox[2]), 4),
                "yMax": round(float(bbox[3]), 4),
                "description": "Averaged normalised bounding box [0,1] from detection head",
            }

        if all_class_probs:
            segmentation_data["classProbs"] = {
                k: round(float(v), 4) for k, v in all_class_probs.items()
            }

        # Three MIL visualizations (plain CT / seg overlay / GradCAM++)
        three_vis = build_three_visualizations(
            input_tensor=runtime._last_input_tensor,
            seg_per_instance=seg_per_instance,
            gradcam_data=gradcam_data,
        )
        if three_vis:
            segmentation_data["plainCt"] = three_vis["plainCt"]
            segmentation_data["segmentationOverlay"] = three_vis["segmentationOverlay"]
            segmentation_data["gradCamOverlay"] = three_vis["gradCamOverlay"]
            # pneumorpheus-app only recognises a single `segmentationData.visualization`
            # block (legacy shape); alias the segmentation-overlay variant into it so
            # the app's slice viewer actually has something to render.
            segmentation_data["visualization"] = _to_app_visualization(three_vis["segmentationOverlay"])
        else:
            # Fallback: single NIfTI visualization for non-MIL inputs
            visualization = build_nifti_visualization(
                file_name=payload.file_name,
                file_bytes=payload.file_bytes,
                runtime_result=runtime_result,
            )
            if visualization:
                segmentation_data["visualization"] = visualization

        nifti_files = _build_nifti_files(
            ct_volume=runtime._last_ct_volume,
            ct_affine=runtime._last_ct_affine,
            mil_indices=runtime._last_mil_indices,
            tumor_mask=tumor_mask,
            seg_ct_volume=self.segmentation_runtime.get_last_ct_volume(),
            seg_affine=self.segmentation_runtime.get_last_affine(),
            gradcam_data=gradcam_data,
        )
        if nifti_files:
            segmentation_data["niftiFiles"] = nifti_files

        findings = _build_findings(predicted_type, confidence, bbox, tnm)
        left_cls, right_cls = _build_classifications(predicted_type, confidence, all_class_probs, bbox)

        return InferenceResponse(
            analysisId=payload.analysis_id,
            patientId=payload.patient_id,
            patientName=payload.patient_name,
            modality=payload.modality,
            clinicianEmail=payload.clinician_email,
            receivedAt=datetime.now(timezone.utc).isoformat(),
            sourceFile=SourceFileMetadata(
                name=payload.file_name,
                mimeType=payload.file_mime_type,
                sizeBytes=payload.file_size_bytes,
            ),
            findings=findings,
            cancerType=predicted_type,
            classificationConfidence=confidence,
            reasoning=reasoning,
            proposedTnmStage=proposed_tnm,
            classifications=[left_cls, right_cls],
            segmentationData=segmentation_data,
            modelInfo={
                "modelName":    model_name,
                "modelVersion": model_version,
                "modelSource":  self.settings.model_source,
                "modelPath":    str(model_path),
            },
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_nifti_files(
    ct_volume: np.ndarray | None,
    ct_affine: np.ndarray | None,
    mil_indices: np.ndarray | None,
    tumor_mask: np.ndarray | None,
    seg_ct_volume: np.ndarray | None,
    seg_affine: np.ndarray | None,
    gradcam_data: tuple[np.ndarray, np.ndarray] | None,
) -> dict[str, Any]:
    files: dict[str, Any] = {}

    if ct_volume is not None and ct_affine is not None:
        files["plainCt"] = build_nifti_file_payload(ct_volume, ct_affine, "plain_ct.nii.gz")

    if tumor_mask is not None and seg_affine is not None and seg_ct_volume is not None:
        try:
            rgb = build_segmentation_overlay_volume(seg_ct_volume, tumor_mask)
            files["segmentationRoi"] = build_rgb_nifti_file_payload(rgb, seg_affine, "segmentation_roi.nii.gz")
        except Exception:
            pass

    if (
        gradcam_data is not None
        and ct_volume is not None
        and ct_affine is not None
        and mil_indices is not None
    ):
        try:
            cam_np, _att_np = gradcam_data
            rgb = build_gradcam_overlay_volume(ct_volume, cam_np, mil_indices)
            files["gradCam"] = build_rgb_nifti_file_payload(rgb, ct_affine, "grad_cam.nii.gz")
        except Exception:
            pass

    return files


def _to_app_visualization(vis: dict[str, Any]) -> dict[str, Any]:
    """Remap a slice-overlay-v1 block's per-slice keys to what pneumorpheus-app's
    AnalysisVisualization component reads (hasOverlay/overlayCoverage instead of
    this server's own hasMask/maskCoverage naming).
    """
    return {
        **vis,
        "slices": [
            {
                **slice_item,
                "hasOverlay": slice_item.get("hasMask", False),
                "overlayCoverage": slice_item.get("maskCoverage", 0.0),
            }
            for slice_item in vis.get("slices", [])
        ],
    }


def _bbox_x_center(bbox: np.ndarray | None) -> float | None:
    """Return normalised x-centre of the bounding box, or None."""
    if bbox is None or len(bbox) < 4:
        return None
    return float((bbox[0] + bbox[2]) / 2.0)


def _build_findings(
    predicted_type: str,
    confidence: float,
    bbox: np.ndarray | None,
    tnm: dict,
) -> str:
    pct = round(confidence * 100)
    text = f"Model predicts {predicted_type} with {pct}% confidence"

    x_center = _bbox_x_center(bbox)
    if x_center is not None:
        side = "left" if x_center < 0.5 else "right"
        text += f". Primary lesion localised to the {side} lung"

    diam = tnm.get("estimated_diameter_mm")
    t_cat = tnm.get("t", "Tx")
    tnm_str = tnm.get("tnm_string", "")
    if diam is not None:
        text += f". Estimated tumour diameter ~{diam} mm ({t_cat})"
    if tnm_str:
        text += f". Staging: {tnm_str}"
        best = tnm.get("best_case_stage", "")
        if best:
            text += f" ({best})"

    text += ". Analysis based on CT morphology, density patterns, and multi-instance attention."
    return text


def _build_classifications(
    predicted_type: str,
    confidence: float,
    all_class_probs: dict[str, float],
    bbox: np.ndarray | None,
) -> tuple[ClassificationItem, ClassificationItem]:
    x_center = _bbox_x_center(bbox)
    if x_center is None or x_center < 0.5:
        primary_side, secondary_side = "Left", "Right"
    else:
        primary_side, secondary_side = "Right", "Left"

    # Differential label for the secondary side
    if all_class_probs:
        others = sorted(
            ((k, v) for k, v in all_class_probs.items() if k != predicted_type),
            key=lambda kv: -kv[1],
        )
        secondary_label = others[0][0] if others else predicted_type
        secondary_conf  = max(0.0, min(1.0, others[0][1])) if others else max(0.0, confidence - 0.05)
    else:
        secondary_label = predicted_type
        secondary_conf  = max(0.0, confidence - 0.05)

    primary = ClassificationItem(
        side=primary_side,
        prediction=predicted_type,
        confidence=confidence,
        explanation=(
            f"Primary lesion detected in the {primary_side.lower()} lung with dominant "
            f"{predicted_type} signature ({round(confidence * 100)}% confidence)."
        ),
    )
    secondary = ClassificationItem(
        side=secondary_side,
        prediction=secondary_label,
        confidence=round(secondary_conf, 4),
        explanation=(
            f"Supporting radiographic evidence in the {secondary_side.lower()} hemi-thorax "
            f"suggests {secondary_label} ({round(secondary_conf * 100)}% confidence)."
        ),
    )
    return primary, secondary


def _resize_mask(mask: np.ndarray, target: int) -> np.ndarray:
    """Bilinear downsample a 2-D probability map to (target, target)."""
    try:
        import torch
        import torch.nn.functional as F

        t = torch.from_numpy(mask).float().unsqueeze(0).unsqueeze(0) # (1,1,H,W)
        t = F.interpolate(t, size=(target, target), mode="bilinear", align_corners=False)
        return t.squeeze().numpy()
    except Exception:
        # Fallback with nearest-neighbour via numpy slicing
        h, w = mask.shape
        step_h = max(1, h // target)
        step_w = max(1, w // target)
        return mask[::step_h, ::step_w][:target, :target]


class InferenceServiceError(RuntimeError):
    pass
